import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import createOrder from './orderApi';

const initialState = {
 orders:[],
  status: 'idle',
  // sirf current order ka track rakhenge so that current order placed hua so that iss 
  currentOrder:null
};

export const createOrderAsync = createAsyncThunk(
  'order/createOrder',
  async (order) => {
    const response = await createOrder(order);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);




export const createOrderSlice = createSlice({
  name: 'order',
  initialState,
  reducers: {
    resetOrder:(state)=>{
      state.currentOrder=null;
     },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(createOrderAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(createOrderAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.orders.push( action.payload);
        // here by this below line you can tell that order has placed successfully and you can show the order success page current order se uski id lene ke liye order number then show karenge  
        state.currentOrder = action.payload;
      })
  },
});



export const {resetOrder} = createOrderSlice.actions;
export const orderReducer = createOrderSlice.reducer;
// pata hoga saare actions se sirf resetOrder vaala hi nikaal rahe hai and reducer ka action nikal rahe hai naam same hona chahiye 